### ISSUE TITLE
Filenames with parantheses in their names are ignored

### ISSUE THREAD

**Issue by robsonsobral** [beville/ComicStreamer#19]
Hi!

I'm testing your software and I found that filenames with `(` or `)` are ignored.

Thanks!

**Comment by davide-romanini** [comment]
I can't reproduce this on linux. Please  provide more information on your environment, giving an example of the ignored file names.

**Comment by robsonsobral** [comment]
I did more tests. It looks like isn't ComixStreamer fault, but of the client.

I'm sorry!
