### ISSUE TITLE
Unable to determine what file/folder is hanging ComicStreamer

### ISSUE THREAD

**Issue by zod-melodic** [beville/ComicStreamer#22]
I'm attempting to add my sorted and unsorted comic folders to ComicStreamer. There is a persistent, repeatable hang when I add my sorted folder at approximately 1500 files in. However, when I check the logs, all I see is 

DEBUG - 200 GET /scanstatus?api_key=XXXXXXXXXXXXXXXXXXXXX (::1) 0.00ms 

over and over again. The number of milliseconds changes, but there's no indication of what file is causing the scan to choke. Help?

**Comment by dogeatdog** [comment]
had the same issue today (first install on Ubuntu 14.04 server, so that was a blast to begin with :D).
Turned out it was a file which had an é in the filename. Changed that to a regular e and all was swell. It will wait endlessly otherwise and never come out of the scanning loop.. So, either check if you can fix the code (I don't know python very well (yet)) to see if you can set the codepage and accept characters which are different from the regular a-z or rename your file(s). I suspect the first would be a better option :D

**Comment by zod-melodic** [comment]
Yeah, I've done a regex search to make sure that there are no non-ASCII characters in the filenames of the comics I'm searching, but it's still hanging on one particular file every time. I can't even tell how ComicStream determines the order in which to scan and add files, so I can't even narrow down the potential offenders.

**Comment by dogeatdog** [comment]
Just a thought, but couldn't you do a console.log type of thing (like I said, coming from Java/javascript background, my Python is very non-existent right now). From another issue ( https://github.com/beville/ComicStreamer/issues/14) you should be able to find the part where it scans for files. What if you just log every entry (I know, it will be a LOT of logging). It would be logical to assume that the last filename to be logged is the one causing the problem ?

**Comment by dogeatdog** [comment]
from server.py :  
   if not opts.no_monitor:
            logging.debug("Going to scan the following folders:")
            for l in self.config['general']['folder_list']:
                logging.debug(u"   {0}".format(repr(l)))

```
        self.monitor = Monitor(self.dm, self.config['general']['folder_list'])
        self.monitor.start()
        self.monitor.scan()
```

That's where it starts the scanning. The scanning itself takes place in monitor.py.
I have to get up in 5 hours, so I'm heading off to bed now, but I would try and put some extra logging in that python method, see what it outputs. I'll try and fumble a bit some tomorrow anyway.

**Comment by dogeatdog** [comment]
I have forked beville's repo and set up PyCharm. Will dive into it tonight. Just need a good primer on everything Python, but that won't be a problem :+1:

**Comment by zod-melodic** [comment]
So what I ended up doing was blowing away the entire library, copying my comic library to a new directory and splitting it into several segments, and then adding each segment one by one to narow down the offending file. I finally found it (whatever was making it hang, it wasn't the filename) and deleted it, and now ComicStreamer works... fine, I guess.
