### ISSUE TITLE
SUGGESTION: json version of pulled data

### ISSUE THREAD

**Issue by cbarrerah** [beville/ComicStreamer#23]
It would be interesting for future app development if there was an option to force all data retrieved to be formatted as json information exchange format.
Something like
/publishers (gets me the web page)
/publishers.json (gets me the json formatted info for publishers)

Is there any option like that available or it's just me and my rumblings? ^.^

**Comment by beville** [comment]
Click on the "API Help" link on the left of the UI for some hints

---

For the a web page with publishers list:

```
/entities/browse/publishers
```

For the JSON list of publishers:

```
/entities/publishers?api_key=XXXXXXXXXXXXXXXXXXXXXXXXX
```

For the JSON list of entities for a particular publisher:

```
/entities/publishers/Marvel?api_key=XXXXXXXXXXXXXXXXXXXXXXXXX
```

For the the first 5 comics for a particular publisher:

```
/entities/publishers/Marvel/comics?per_page=5&api_key=XXXXXXXXXXXXXXXXXXXXXXXXX
```

For the the next 5 comics for that same publisher:

```
/entities/publishers/Marvel/comics?offset=5&per_page=5&api_key=XXXXXXXXXXXXXXXXXXXXXXXXX
```

Hope this helps!

**Comment by beville** [comment]
Also note that you can omit the "api_key" parameter if you haven't configured it.

**Comment by cbarrerah** [comment]
Exactly what i was asking for ^.^
Thanks!
