### ISSUE TITLE
Export library to excel or file containing library?

### ISSUE THREAD

**Issue by thegreenlantern71** [beville/ComicStreamer#51]
Is there a way (not counting copy of every page and pasting to Excel) to export the ComicStreamer library to Excel? Alternatively, is there a specific file in the existing folder structure that contains the library itself that can be opened in Notepad and moved into Excel?

Thanks.

**Comment by ghost** [comment]
google.. 

sqlite export to excel

or 

sqlite export to cvs

database file is in the folder

```
On Linux: "~/.ComicStreamer"
On Mac OS: "~/Library/Application Support/ComicStreamer"
On Windows: "%APPDATA%\ComicStreamer"
```

**Comment by thegreenlantern71** [comment]
Thank you!! (^_^)
