### ISSUE TITLE
Duplicate folder matching needs some work

### ISSUE THREAD

**Issue by wyldphyre** [beville/ComicStreamer#6]
Firstly, nice bit of work with this. It's going to be handy in the future. I'm looking forward to when it's polished up and had cosmetic improvements.

I've found a case where two different folders can't be configured, presumably because they start with the same string and/or the fact that one has a space in it. The folders in question are:

/Volumes/Storage/Media/Manga
/Volumes/Storage/Media/Manga (Ongoing)

I've tried using \ to escape the space and quoting the folder with a space but I always end up with the "one folder can't contain another" error message.

**Comment by wyldphyre** [comment]
Pretty sure the problem is with the use of .StartsWith in line 1011 of server.py. I'm not a python dev so I'm not sure what the proper solution would be.

**Comment by beville** [comment]
Thanks for finding this.  Was a simple fix that's checked in.  If you're using a binary package, it will be in the next release.

**Comment by wyldphyre** [comment]
Can confirm this is fixed in the 0.6 release
